// Guards the packaging step with an explanation instead of npm's or
// electron-builder's version of the same failure.
//
// Two things it checks, both of which are uninformative when they break:
//
//   * node_modules is gitignored, so a fresh clone has nothing installed and
//     every script here dies with "'electron' is not recognized as an internal
//     or external command".
//   * Two files of the bundled pack -- pack-manifest.json and launchers/ -- are
//     generated by tools/build.py and gitignored too, so `npm run dist` from a
//     fresh clone fails inside electron-builder on a `from` path that does not
//     exist. That failure names neither the file's purpose nor the fix.
//
// Note this is the *shell* only, and it is not the app's own runtime check. The
// app verifies Python and the pack at startup with real dialogs, because those
// can be missing on a user's machine rather than on the build machine.
const { existsSync } = require("node:fs");
const { join, resolve } = require("node:path");

// What electron-builder copies to resources/pack: enough of a pack for a first
// run to fetch the rest. Anything the app cannot start without belongs here.
const BOOTSTRAP = [
  "serve.py",
  "installer.py",
  "iwadfinder.py",
  "fetcher.py",
  "sources.json",
  "pack-manifest.json",
  "launchers",
  "art",
  "app/index.html",
];

function checkBootstrap() {
  const pack = resolve(__dirname, "..");
  const missing = BOOTSTRAP.filter((rel) => !existsSync(join(pack, rel)));
  if (!missing.length) return;

  console.error(`
cannot package: ${missing.length} file(s) of the bundled pack are missing.

The installer ships serve.py and the built UI so a first run can fetch the
3.4 GB payload. Some of them are generated rather than committed, so this has
to be built where a full pack exists:

  ${missing.map((m) => join(pack, m)).join("\n  ")}

Build the pack and the UI first, then the app:

    python tools\\build.py     # writes pack-manifest.json and launchers/
    npm run build             # writes app/, the launcher UI
    cd desktop && npm run dist
`);

  process.exit(1);
}

if (!existsSync(join(__dirname, "node_modules"))) {
  console.error(`
electron is missing: desktop/node_modules does not exist.

The desktop shell is optional. The launcher already runs with no Electron at
all, just a browser tab:

    python serve.py

To build the desktop app, install the build tooling once:

    cd desktop
    npm ci
    npm run dist

That produces an installer in desktop/release/. The app ships its own Python and
fetches the 3.4 GB pack on first run -- Electron is the window, not the game.
`);

  process.exit(1);
}

checkBootstrap();
